[build-system]
requires = ["hatchling >= 1.29"]
build-backend = "hatchling.build"

[project]
name = "corvs"
version = "1.0.0"
description = "Implementation of CorVS+"
readme = "README.md"
authors = [
    { name = "Kazuma Kano", email = "kazuma@ucl.nuee.nagoya-u.ac.jp" }
]
license-files = ["LICENSE"]

requires-python = ">=3.11, <3.12"
dependencies = [
    "einops>=0.8.2",
    "lightning>=2.6.1",
    "numba>=0.64.0",
    "numpy>=2.4.2",
    "omegaconf>=2.3.0",
    "pandas>=3.0.1",
    "python-dateutil>=2.9.0.post0",
    "pytorch_optimizer>=3.10.0",
    "safetensors>=0.7.0",
    "scipy>=1.17.1",
    "torch==2.9.1",
    "torchao==0.15.0",
    "torchtune>=0.6.1",
    "torchvision==0.24.1",
]

[project.optional-dependencies]
train = [
    "setuptools==81.0.0",
    "tensorboard>=2.20.0",
]

[project.urls]
Paper = ""
Dataset = "https://doi.org/10.5281/zenodo.17745683"
Code = "https://github.com/kazumakano/corvs-plus"
