# data
freq: 10
smooth: 0.2
min_in_len: 21
win_len: 600
win_st: 10
pos_factor: 4
pos_mask: 0.275
pos_shift: 0.25
neg_ratio: 1024

# architecture
arch: corvsnet
cnn_sep: false
cnn_ks_s: 5
cnn_fn: null
cnn_act: silu
cls_tok: false
xformer_pos_enc: rope
xformer_n_layers: 4
xformer_d_model: 48
xformer_nhead: 4
xformer_d_ff: 128
xformer_dr: 0.1
xformer_act: gelu
xformer_norm: layer
time_agg: attn_pool
mlp_dr: 0.1
mlp_act: gelu

# training
loss: bce
opt: adamw
sched: warm_cos
lr: 0.0001
batch_size: 128
max_step: 100000
val_step: 1000
warm_step: 5000
patience: 10
num_workers: 4
